words = [
    "bluesky", "bsky", "endfor", "shitposting", "codeberg", "quickshell", "niri", "qml", "malloc",
    "dms", "caelestia", "hyperfixation", "fanart", "frieren", "pfp", "silksong", "terraria",
    "Subnautica", "bocchi", "cypariss", "ost", "neovim", "hoverable", "upscaling", "tbd", "chilen",
    "mpris", "ipc", "CLI"
]
