words = [
    "bluesky", "bsky", "endfor", "shitposting", "codeberg", "quickshell", "niri", "qml", "malloc",
    "dms", "caelestia", "hyperfixation", "fanart", "frieren", "pfp", "silksong", "terraria",
    "Subnautica", "bocchi"
]
